export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const ENABLE_SEARCH_LOADER = 'ENABLE_SEARCH_LOADER';
export const DISABLE_SEARCH_LOADER = 'DISABLE_SEARCH_LOADER';
